export const General = {
  dashboard:'Dashboard',
  invoices:'Invoices',
  customers:'Customers',
  plans:'Plans',
  integrations:'Integrations',
  setup:'Setup',
  support:'Support',
  plansDes:'Manage your team members and their account permissions here.',
  name:'Name',
  status:'Status',
  SETUPFEE:'SETUP FEE',
  trial:'Trial',
  dateCreated:'Date Created',
  createPlanCategory:'Create Plan Category',
  createPlan:'Create Plan',
  edit:'Edit',
  save:'Save',
  Active:'Active',
  Disabled:'Disabled',
  Paused:'Paused',
  general:'General',
  planName:'Plan Name',
  planNameAr:'Plan Name(AR)',
  planCode:'Plan Code',
  planDescription:'Plan Description',
  category:'Category',
  trialConfigurations:'Trial Configurations',
  freeTrial:'Free Trial',
  pricingAndBilling:'Pricing And Billing',
  action:'Action',
  bullingCycles:'Bulling Cycles',
  price:'Price',
  renewals:'Renewals',
  autoRenewal:'Auto Renewal',
  autoRenewalDesc:'Automatically renew the Subscription after the cycle is ended',
  expireSubscription:'Expire Subscription',
  expireSubscriptionDesc:'Automatically Expires the Subscription after the cycle is ended',
  fees:'Fees',
  setupFee:'Setup Fee',
  accountingCode:'Accounting Code',
  redirectURL:'Redirect URL',
  redirectTo:'Redirect to',
  planStatus:'Plan Status',
  exStarterPlan:'ex. Starter Plan',
  exStarterPlanAr:'مثال:الباقة الإفتتاحية',
  starterP:'StarterP',
  planForBeginning:'Plan for the big beginning',
  freeTrialHint:'Days before starting the cycle',
  redirectHintOne:"Redirect to your Preferred URL",
  redirectHintTwo:'Your customer will be redirected to this url after successful purchases.',
  planNameHint:'The Plan Name in English',
  planNameHintAr:'plan Name Hint Ar',
  redirectUrlHint:'redirect Url Hint',
  planCategory:'Plan Category',
  categoryName:'Category Name',
  categoryDescription:'Category Description',
  exB2CCustomers:'ex. B2C Customers',
  categoryDescriptionPlaceholder:'This Plan is made for B2C customers',
  categoryStatus:'Category Status',
  editCategory:'Edit Category',
  categoryAddMsg:'The category add successfully',
  categoryEditMsg:'The category edit successfully',
  planAddMsg:'The plan add successfully',
  planEditMsg:'The plan edit successfully',
  model:"Model",
  fixedPrice:"Fixed Price",
  dynamicPrice:"Dynamic Price",
  SAR:"SAR",
  notFound:'No Data to show',
  days:'Days',
  billed:'Billed',
  each:'Each',
  link:"Link",
  addCustomer:"Add customer",
  totalCustomerAccounts:"Total Customer Accounts",
  searchForOrder:"Search for order",
  search:"Search",
  plan:"Plan",
  dateJoined:"Date Joined",
  subscriptionExpiry:"Subscription Expiry",
  active:'Active',
  cancelled:"Cancelled",
  future:"Future",
  expired:"Expired",
  nonRenewing:"Non Renewing",
  newCustomer:"New Customer",
  info:"info",
  subscription:"Subscription",
  logs:"Logs",
  mainInfo:"Main info",
  customerName:"Customer Name",
  customerKey:"Customer key",
  customerKeyHint:"This is the key to identify the user",
  customerDescription:"Customer Description",
  customerDescriptionPlaceholder:"Plan for the big beginning",
  customerSince:"Customer since",
  joinedSubnowOn:"Joined Subnow on",
  contactInfo:"Contact info",
  customerEmail:"Customer Email",
  customerEmailHint:"We send Emails to this Address",
  customerPhone:"Customer Phone",
  customerPhoneHint:"We send SMS to this Address",
  preferredLanguage:"Preferred Language",
  customerTaxInformations:"Customer Tax Informations",
  isABusiness:"Is a Business",
  companyRegistrationNumber:"Company registration Number",
  taxID:"Tax ID",
  address:"Address",
  city:"City",
  stateProvince:"State / Province",
  state:"State",
  country:"Country",
  customerKeyTooltip:"This is the Customer Identification field",
  customerEmailTooltip:"We will send Subscription related emails to this Email Address",
  customerPhoneTooltip:"We will send Subscription related messages to this Phone Number",
  companyRegistrationNumberTooltip:"Government’s Company registration Number",
  taxIDTooltip:"Government’s Tax Identification Number",
  RequiredInput: 'This field is required',
  InvalidEmail: 'Enter a valid email',
  InvalidPattern: 'Enter the data correctly',
  invalid : 'Invalid data',
  invalidContactUsName: 'The field must be in English and without symbols',
  ThisFieldMustBeLessOrEqual: 'The value of this field must be less than or equal to {0}.',
  maxlength: 'The maximum number of characters is {0}',
  customerAddMsg:'The customer add successfully',
  customerEditMsg:'The customer edit successfully',
  customer:"Customer",
  urlNotValid:"This link not valid",
  subscriptionPlan:"Subscription Plan",
  createSubscription:"Create Subscription",
  chargeTotalAmount:"Charge Total Amount",
  chargeTotalAmountHint:"The amount you charge every Billing Cycle",
  nextInvoice:"Next Invoice",
  activationInvoiceHint:"",
  copy:"Copy",
  expiryDate:"Expiry Date",
  subscriptionBillingCycle:"Subscription Billing Cycle",
  subscriptionBillingCycleHint:"Billing Starts when Expiry Date is due",
  changeSubscription:"Change Subscription",
  update:"Update",
  selectPlan:"Select Plan",
  chooseTheBillingCycle:"Choose the Billing Cycle",
  startDate:"Start Date",
  updateSubscriptionExpiryDate:"Update Subscription Expiry Date",
  newExpiryDate:"New Expiry Date",
  updateExpiryDate:"Update Expiry Date",
  updateSubscription:"Update Subscription",
  theNewPlan:"The New Plan",
  startDateValid:'Start Date must be less than or equal to Expiry Date.',
  expiryDateValid:'Expiry Date Greater than or equal start date',
  updateExpiryDateSuccessfully:"Update expiry date successfully",
  updateSubscriptionSuccessfully:"Update subscription successfully",
  subscriptionAddMsg:"Subscription added successfully",
  newExpiryDateTooltip:"This is the date the current Billing Cycle will end",
  companySettings:"Company Settings",
  companySettingsHint:"Setup general settings about your company",
  branding:"Branding",
  brandingHint:"Design the custom page of your invoice",
  sms:"SMS",
  smsHint:"Design the custom page of your invoice",
  payments:"Payments",
  paymentsHints:"Apply Taxes on plans or Items",
  company:"Company",
  companyName:"Company Name",
  companyNameHint:"This will be displayed on your profile.",
  description:"Description",
  descriptionCompanyHint:"A quick snapshot of your company.",
  describeCompany:"Describe your Company to your users",
  describeCompanyHint:"characters left",
  companyTaxInformations:"Company Tax Informations",
  addressLine1:"Address Line 1",
  streetName:"Street Name",
  addressLine2:"Address Line 2",
  buildingName:"Building Name",
  postalCode:"Postal Code",
  companyEditSuccessfully:"Company edit successfully",
  companyLogo:"Company logo",
  companyLogoHint:"Update your company logo and then choose where you want it to display.",
  urlSubdomain:"URL Subdomain",
  urlSubdomainHint:"This is the link your customers will use",
  subdomain:"Subdomain",
  subdomainTooltip:"This is the default link which Pay links and Invoices will redirect to",
  subnow:"subnow.io/",
  subdomainHint:"To change Subdomain you have to contact Subnow support",
  theme:"Theme",
  logoBackgroundColor:"Logo Background Color",
  primaryPayButtonColor:"Primary Pay Button Color",
  supportLink:"Support link",
  supportLinkHint:"Your Customers will go to this link if they needed support",
  legal:"Legal",
  privacyPolicyURL:"Privacy policy URL",
  privacyPolicyURLTooltip:"Add the link to your privacy policy",
  termsServiceURL:"Terms of Service URL",
  termsServiceURLTooltip:"Add the link to your Terms of Use/Service.",
  socialProfile:"Social profiles",
  addLink:"Add Link",
  xCom:"X.com",
  facebook:"Facebook",
  instagram:"Instagram",
  linkedin:"Linkedin",
  whatsappNumber:"Whatsapp Number",
  addWhatsappNumber:"Add whatsapp phone number",
  addWhatsappNumberHint:"Include International key number (example: +96650000000)",
  invalidWhatsappNumber:"Number should include international key number (example: +96650000000)",
  remove:"Remove",
  http:"http://",
  imageErrorSizeDimensions:'image size should be 512x512px',
  firstBillingCycleInvoice:"First Billing Cycle Invoice",
  markAsPaid:"Mark as Paid",
  customerStartsImmediately:"Customer Starts Immediately",
  order:"Order",
  onPayLink:"On Paylink",
  plansVisibility:"Plans Visibility",
  plansVisibilityHint:"Customize Plans Sorting order, And which plans should be visible to your customers in their Paylinks.",
  billingCycle:"Billing Cycle",
  poweredBy:"Powered by",
  terms:"Terms",
  privacy:"Privacy",
  subtotal:"Subtotal",
  vat:"VAT(15%)",
  total:"Total",
  totalDue:"Total due",
  pay:"Pay",
};
