export const General = {
  dashboard:'Dashboard',
  invoices:'Invoices',
  customers:'Customers',
  plans:'Plans',
  integrations:'Integrations',
  setup:'Setup',
  support:'Support',
  plansDes:'Manage your team members and their account permissions here.',
  name:'Name',
  status:'Status',
  SETUPFEE:'SETUP FEE',
  trial:'Trial',
  dateCreated:'Date Created',
  createPlanCategory:'Create Plan Category',
  createPlan:'Create Plan',
  edit:'Edit',
  save:'Save',
  Active:'Active',
  Disabled:'Disabled',
  Paused:'Paused',
  general:'General',
  planName:'Plan Name',
  planNameAr:'Plan Name(AR)',
  planCode:'Plan Code',
  planDescription:'Plan Description',
  category:'Category',
  trialConfigurations:'Trial Configurations',
  freeTrial:'Free Trial',
  pricingAndBilling:'Pricing And Billing',
  action:'Action',
  bullingCycles:'Bulling Cycles',
  price:'Price',
  renewals:'Renewals',
  autoRenewal:'Auto Renewal',
  autoRenewalDesc:'Automatically renew the Subscription after the cycle is ended',
  expireSubscription:'Expire Subscription',
  expireSubscriptionDesc:'Automatically Expires the Subscription after the cycle is ended',
  fees:'Fees',
  setupFee:'Setup Fee',
  accountingCode:'Accounting Code',
  redirectURL:'Redirect URL',
  redirectTo:'Redirect to',
  planStatus:'Plan Status',
  exStarterPlan:'ex. Starter Plan',
  exStarterPlanAr:'مثال:الباقة الإفتتاحية',
  starterP:'StarterP',
  planForBeginning:'Plan for the big beginning',
  freeTrialHint:'Days before starting the cycle',
  redirectHint:'Redirect to your Preferred URL Your customer will be redirected to this url after successful purchases.',
  planNameHint:'The Plan Name in English',
  planNameHintAr:'plan Name Hint Ar',
  redirectUrlHint:'redirect Url Hint',
  planCategory:'Plan Category',
  categoryName:'Category Name',
  categoryDescription:'Category Description',
  exB2CCustomers:'ex. B2C Customers',
  categoryDescriptionPlaceholder:'This Plan is made for B2C customers',
  categoryStatus:'Category Status',
  editCategory:'Edit Category',
  categoryAddMsg:'The category add successfully',
  categoryEditMsg:'The category edit successfully',
  planAddMsg:'The plan add successfully',
  planEditMsg:'The plan edit successfully',
  model:"Model",
  fixedPrice:"Fixed Price",
  dynamicPrice:"Dynamic Price",
  SAR:"SAR",
  notFound:'No Data to show',
  days:'Days',
  billed:'Billed',
  each:'Each',
  link:"Link",
  addCustomer:"Add customer",
  totalCustomerAccounts:"Total Customer Accounts",
  searchForOrder:"Search for order",
  plan:"Plan",
  dateJoined:"Date Joined",
  subscriptionExpiry:"Subscription Expiry",
  cancelled:"Cancelled",
  future:"Future",
  expired:"Expired",
  nonRenewing:"Non Renewing",
  newCustomer:"New Customer",
  info:"info",
  subscription:"Subscription",
  logs:"Logs",
  mainInfo:"Main info",
  customerName:"Customer Name",
  customerKey:"Customer key",
  customerKeyHint:"This is the key to identify the user",
  customerDescription:"Customer Description",
  customerDescriptionPlaceholder:"Plan for the big beginning",
  customerSince:"Customer since",
  joinedSubnowOn:"Joined Subnow on",
  contactInfo:"Contact info",
  customerEmail:"Customer Email",
  customerEmailHint:"We send Emails to this Address",
  customerPhone:"Customer Phone",
  customerPhoneHint:"We send SMS to this Address",
  preferredLanguage:"Preferred Language",
  customerTaxInformations:"Customer Tax Informations",
  isABusiness:"Is a Business",
  companyRegistrationNumber:"Company registration Number",
  taxID:"Tax ID",
  address:"Address",
  city:"City",
  stateProvince:"State / Province",
  state:"State",
  country:"Country",
  customerKeyTooltip:"This is the Customer Identification field",
  customerEmailTooltip:"We will send Subscription related emails to this Email Address",
  customerPhoneTooltip:"We will send Subscription related messages to this Phone Number",
  companyRegistrationNumberTooltip:"Government’s Company registration Number",
  taxIDTooltip:"Government’s Tax Identification Number",
};
