export const General = {
  dashboard:'Dashboard',
  invoices:'Invoices',
  customers:'Customers',
  plans:'Plans',
  integrations:'Integrations',
  setup:'Setup',
  support:'Support',
  plansDes:'Manage your team members and their account permissions here.',
  name:'Name',
  status:'Status',
  SETUPFEE:'SETUP FEE',
  trial:'Trial',
  dateCreated:'Date Created',
  createPlanCategory:'Create Plan Category',
  createPlan:'Create Plan',
  edit:'Edit',
  save:'Save',
  Active:'Active',
  Disabled:'Disabled',
  Paused:'Paused',
  general:'General',
  planName:'Plan Name',
  planNameAr:'Plan Name(AR)',
  planCode:'Plan Code',
  planDescription:'Plan Description',
  category:'Category',
  trialConfigurations:'Trial Configurations',
  freeTrial:'Free Trial',
  pricingAndBilling:'Pricing And Billing',
  action:'Action',
  bullingCycles:'Bulling Cycles',
  price:'Price',
  renewals:'Renewals',
  autoRenewal:'Auto Renewal',
  autoRenewalDesc:'Automatically renew the Subscription after the cycle is ended',
  expireSubscription:'Expire Subscription',
  expireSubscriptionDesc:'Automatically Expires the Subscription after the cycle is ended',
  fees:'Fees',
  setupFee:'Setup Fee',
  accountingCode:'Accounting Code',
  redirectURL:'Redirect URL',
  redirectTo:'Redirect to',
  planStatus:'Plan Status',
  exStarterPlan:'ex. Starter Plan',
  exStarterPlanAr:'مثال:الباقة الإفتتاحية',
  starterP:'StarterP',
  planForBeginning:'Plan for the big beginning',
  freeTrialHint:'Days before starting the cycle',
  planNameHint:'plan Name Hint',
  planNameHintAr:'plan Name Hint Ar',
  redirectUrlHint:'redirect Url Hint',
  planCategory:'Plan Category',
  categoryName:'Category Name',
  categoryDescription:'Category Description',
  exB2CCustomers:'ex. B2C Customers',
  categoryDescriptionPlaceholder:'This Plan is made for B2C customers',
  categoryStatus:'Category Status',
  editCategory:'Edit Category',
  categoryAddMsg:'The category add successfully',
  categoryEditMsg:'The category edit successfully',
  model:"Model",
  fixedPrice:"Fixed Price",
  dynamicPrice:"Dynamic Price",
  SAR:"SAR"



};
