export const General = {
  dashboard:'الرئسية',
  invoices:'الفواتير',
  customers:'العملاء',
  plans:'الباقات',
  integrations:'الدمج',
  setup:'الإعدادات',
  support:'الدعم',
  plansDes:'إدارة أعضاء فريقك وأذونات حساباتهم هنا.',
  name:'الاسم',
  status:'الحالة',
  SETUPFEE:'رسوم الإعداد',
  trial:'محاوله',
  dateCreated:'تاريخ الإنشاء',
  createPlanCategory:'إنشاء فئة الباقه',
  createPlan:'إنشاء باقه',
  edit:'تعديل',
  save:'حفظ',
  Active:'نشط',
  Disabled:'معطل',
  Paused:'متوقف مؤقتا',
  general:'عام',
  planName:'اسم الباقه',
  planNameAr:'اسم الباقه بالعربي',
  planCode:'كود الباقه',
  planDescription:'وصف الباقه',
  category:'الفئة',
  trialConfigurations:'تجربة الاعدادات',
  freeTrial:'تجربة مجانية',
  pricingAndBilling:'السعر والفواتير',
  action:'الإجراء',
  bullingCycles:'كشف الحسابات والتحصيل',
  price:'السعر',
  renewals:'التجديدات',
  autoRenewal:'التجديد التلقائي',
  autoRenewalDesc:'تجديد الاشتراك تلقائيا بعد انتهاء الدورة',
  expireSubscription:'انتهاء الاشتراك',
  expireSubscriptionDesc:'انتهاء صلاحية الاشتراك تلقائيًا بعد انتهاء الدورة',
  fees:'الرسوم',
  setupFee:'رسوم الإعداد',
  accountingCode:'كود المحاسبة',
  redirectURL:'إعادة توجيه URL',
  redirectTo:'إعادة التوجيه إلى',
  planStatus:'حالة الباقه',
  exStarterPlan:'ex. Starter Plan',
  exStarterPlanAr:'مثال:الباقة الإفتتاحية',
  starterP:'StarterP',
  planForBeginning:'الباقه للبداية',
  freeTrialHint:'قبل أيام من بدء الدورة',
  redirectHintOne:"إعادة التوجيه إلى الرابط المفضل",
  redirectHintTwo:'لديك سيتم توجيه عميلك إلى هذا الرابط بعد إتمام الشراء بنجاح.',
  planNameHint:'اسم الباقه باللغة الإنجليزية',
  planNameHintAr:'plan Name Hint Ar',
  redirectUrlHint:'إعادة توجيه URL',
  planCategory:'فئة الباقه',
  categoryDescription:'وصف التصنيف',
  categoryName:'اسم الفئة',
  exB2CCustomers:'ex. B2C Customers',
  categoryDescriptionPlaceholder:'تم إعداد هذه الخطة لعملاء B2C',
  categoryStatus:'حالة الفئة',
  editCategory:'تعديل الفئه',
  categoryAddMsg:'تم أضافة التصنيف بنجاح ',
  categoryEditMsg:'تم تعديل التصنيف بنجاح ',
  planAddMsg:'تم أضافة الباقه بنجاح',
  planEditMsg:'تم تعديل الباقه بنجاح',
  model:"نموذج",
  fixedPrice:"سعر ثابت",
  dynamicPrice:"سعر متغير",
  SAR:"ريال",
  notFound: 'لا توجد بيانات لإظهارها.',
  days:'يوم',
  billed:'دفع',
  each:'كل',
  link:'الرابط',
  addCustomer:"إضافة العميل",
  totalCustomerAccounts:"إجمالي حسابات العملاء",
  searchForOrder:"بحث بالترتيب",
  search:"بحث",
  plan:"باقه",
  dateJoined:"تاريخ الانضمام",
  subscriptionExpiry:"انتهاء الاشتراك",
  active:'نشط',
  cancelled:"ملغي",
  future:"مستقبل",
  expired:"منتهي",
  nonRenewing:"غير مجدد",
  newCustomer:"عميل جديد",
  info:"معلومات",
  subscription:"الاشتراك",
  logs:"السجلات",
  mainInfo:"المعلومات الرئيسية",
  customerName:"اسم العميل",
  customerKey:"مفتاح العميل",
  customerKeyHint:"هذا هو المفتاح لتحديد هوية المستخدم",
  customerDescription:"وصف العميل",
  customerDescriptionPlaceholder:"باقات للبدايه الكبيرة",
  customerSince:"العميل منذ",
  joinedSubnowOn:"انضم إلى Subnow بتاريخ",
  contactInfo:"معلومات الاتصال",
  customerEmail:"البريد الإلكتروني للعميل",
  customerEmailHint:"نقوم بإرسال رسائل البريد الإلكتروني إلى هذا العنوان",
  customerPhone:"هاتف العميل",
  customerPhoneHint:"نرسل SMS إلى هذا العنوان",
  preferredLanguage:"اللغة المفضلة",
  customerTaxInformations:"المعلومات الضريبية للعملاء",
  isABusiness:"هل عمل تجاري",
  companyRegistrationNumber:"رقم تسجيل الشركة",
  taxID:"الرقم الضريبي",
  address:"العنوان",
  city:"المدينة",
  stateProvince:"الولاية / المحافظة",
  state:"ولاية",
  country:"دولة",
  customerKeyTooltip:"هذا هو حقل تحديد هوية العميل",
  customerEmailTooltip:"سوف نقوم بإرسال رسائل البريد الإلكتروني المتعلقة بالاشتراك إلى عنوان البريد الإلكتروني هذا",
  customerPhoneTooltip:"سوف نقوم بإرسال رسائل متعلقة بالاشتراك إلى رقم الهاتف هذا",
  companyRegistrationNumberTooltip:"رقم تسجيل الشركة الحكومية",
  taxIDTooltip:"رقم الهوية الضريبية للحكومة",
  RequiredInput: 'هذا الحقل مطلوب',
  InvalidEmail: 'ادخل بريد الكتروني صحيح',
  InvalidPattern: 'ادخل البيانات بطريقة صحيحة',
  invalid: 'غير صالح',
  invalidContactUsName: 'يجب أن يكون الاسم باللغة العربية وبدون استخدام رموز',
  ThisFieldMustBeLessOrEqual: 'هذا الحقل يجب ان يقل او يساوي {0}',
  ThisFieldMustBeAStringOrArrayTypeWithAMaximumLengthOf: 'الحد الاقصى للحروف هو {0}',
  customerAddMsg:'تم أضافة العميل بنجاح',
  customerEditMsg:'تم تعديل العميل بنجاح',
  customer:"عميل",
  urlNotValid:"هذا الرابط غير صحيح",
  subscriptionPlan:"باقه الاشتراك",
  createSubscription:"انشاء اشتراك",
  chargeTotalAmount:"شحن المبلغ الإجمالي",
  chargeTotalAmountHint:"المبلغ الذي تتقاضاه في كل  فوترة",
  nextInvoice:"الفاتورة القادمة",
  activationInvoiceHint:"",
  copy:"نسخ",
  expiryDate:"تاريخ الانتهاء",
  subscriptionBillingCycle:"دورة فواتير الاشتراك",
  subscriptionBillingCycleHint:"تبدأ الفواتير عندما يحين تاريخ انتهاء الصلاحية",
  changeSubscription:"تحديث الاشتراك",
  update:"تحديث",
  selectPlan:"اختار الباقه",
  chooseTheBillingCycle:"اختر الفوترة",
  startDate:"تاريخ البدء",
  updateSubscriptionExpiryDate:"تحديث تاريخ انتهاء الاشتراك",
  newExpiryDate:"تاريخ انتهاء جديد",
  updateExpiryDate:"تاريخ انتهاء التحديث",
  updateSubscription:"تحديث الاشتراك",
  theNewPlan:"الباقة الجديده",
  startDateValid:'يجب أن يكون تاريخ البدء أقل من أو يساوي تاريخ انتهاء الصلاحية',
  expiryDateValid:'يجب أن يكون ناريخ الانتهاء آكبر من أو يساوي تاريخ البدء',
  updateExpiryDateSuccessfully:"تم تحديث تاريخ انتهاء الصلاحية بنجاح",
  updateSubscriptionSuccessfully:"تم تحديث الاشتراك بنجاح",
  subscriptionAddMsg:"تمت إضافة الاشتراك بنجاح",
  newExpiryDateTooltip:"هذا هو التاريخ الذي ستنتهي فيه دورة الفوترة الحالية",
  companySettings: "إعدادات الشركة",
  companySettingsHint: "قم بإعداد الإعدادات العامة لشركتك",
  branding: "العلامة التجارية",
  brandingHint: "صمم الصفحة المخصصة لفاتورتك",
  sms: "الرسائل النصية القصيرة",
  smsHint: "صمم الصفحة المخصصة لفاتورتك",
  payments: "المدفوعات",
  paymentsHints: "تطبيق الضرائب على الخطط أو العناصر",
  company:"الشركة",
  companyName: "اسم الشركة",
  companyNameHint: "سيتم عرض هذا على ملفك الشخصي.",
  description: "الوصف",
  descriptionCompanyHint: "لمحة سريعة عن شركتك.",
  describeCompany: "وصف شركتك لمستخدميك",
  describeCompanyHint: "بقي عدد من الأحرفً",
  companyTaxInformations: "معلومات الضريبة للشركة",
  addressLine1: "العنوان الأول",
  streetName: "اسم الشارع",
  addressLine2: "العنوان الثاني",
  buildingName: "اسم المبنى",
  postalCode: "الرمز البريدي",
  companyEditSuccessfully:"تم تعديل الشركة بنجاح",
  companyLogo: "شعار الشركة",
  companyLogoHint: "حدث شعار شركتك ثم اختر المكان الذي تريد عرضه فيه.",
  urlSubdomain: "رابط النطاق الفرعي",
  urlSubdomainHint: "هذا هو الرابط الذي سيستخدمه عملاؤك",
  subdomain: "النطاق الفرعي",
  subdomainTooltip: "هذا هو الرابط الافتراضي الذي سيتم إعادة توجيه روابط الدفع والفواتير إليه",
  subnow: "/subnow.io",
  subdomainHint: "لتغيير النطاق الفرعي، عليك الاتصال بدعم Subnow",
  theme: "الثيم",
  logoBackgroundColor: "لون خلفية الشعار",
  primaryPayButtonColor: "لون زر الدفع الأساسي",
  supportLink: "رابط الدعم",
  supportLinkHint: "سيذهب عملاؤك إلى هذا الرابط إذا احتاجوا إلى الدعم",
  legal: "قانوني",
  privacyPolicyURL: "رابط سياسة الخصوصية",
  privacyPolicyURLTooltip: "أضف رابط سياسة الخصوصية الخاصة بك",
  termsServiceURL: "رابط شروط الخدمة",
  termsServiceURLTooltip: "أضف رابط شروط الاستخدام/الخدمة الخاصة بك.",
  socialProfile: "الملفات الاجتماعية",
  addLink: "إضافة رابط",
  xCom: "X.com",
  facebook: "فيسبوك",
  instagram: "إنستغرام",
  linkedin: "لينكد إن",
  whatsappNumber: "رقم واتساب",
  addWhatsappNumber: "أضف رقم هاتف واتساب",
  addWhatsappNumberHint: "تضمين مفتاح الرقم الدولي (مثال: +96650000000)",
  invalidWhatsappNumber:"يجب أن يتضمن الرقم المفتاح الدولي (مثال: +96650000000)",
  remove: "إزالة",
  http: "http://",
  imageErrorSizeDimensions:"حجم الصورة يجب أن يكون 512x512 بكسل.",
  firstBillingCycleInvoice: "الفاتورة الاولي للدفع",
  markAsPaid: " مدفوعة",
  customerStartsImmediately: "يبدأ العميل فورًا",
  plansVisibility:"رؤية الباقات",
  plansVisibilityHint:"تخصيص ترتيب فرز الباقات، وما هي الباقات التي ينبغي أن تكون مرئية لعملائك في روابط الدفع الخاصة بهم.",
  billingCycle: "دورة الفوترة",
  poweredBy: "مشغل بواسطة",
  terms: "الشروط",
  privacy: "الخصوصية",
  subtotal: "الإجمالي الفرعي",
  vat: "ضريبة القيمة المضافة (15%)",
  total: "المجموع",
  totalDue: "الإجمالي المستحق",
  pay: "الدفع",
  deactivated:"غير مفعل"
};
