export const General = {
  dashboard:'الرئسية',
  invoices:'الفواتير',
  customers:'العملاء',
  plans:'الخطط',
  integrations:'الدمج',
  setup:'الإعدادات',
  support:'الدعم',
  plansDes:'إدارة أعضاء فريقك وأذونات حساباتهم هنا.',
  name:'الاسم',
  status:'الحالة',
  SETUPFEE:'رسوم الإعداد',
  trial:'محاوله',
  dateCreated:'تاريخ الإنشاء',
  createPlanCategory:'إنشاء فئة الخطة',
  createPlan:'إنشاء خطة',
  edit:'تعديل',
  save:'حفظ',
  Active:'نشط',
  Disabled:'معطل',
  Paused:'متوقف مؤقتا',
  general:'عام',
  planName:'اسم الخطة',
  planNameAr:'اسم الخطة بالعربي',
  planCode:'كود الخطة',
  planDescription:'وصف الخطة',
  category:'الفئة',
  trialConfigurations:'تجربة الاعدادات',
  freeTrial:'تجربة مجانية',
  pricingAndBilling:'السعر والفواتير',
  action:'الإجراء',
  bullingCycles:'كشف الحسابات والتحصيل',
  price:'السعر',
  renewals:'التجديدات',
  autoRenewal:'التجديد التلقائي',
  autoRenewalDesc:'تجديد الاشتراك تلقائيا بعد انتهاء الدورة',
  expireSubscription:'انتهاء الاشتراك',
  expireSubscriptionDesc:'انتهاء صلاحية الاشتراك تلقائيًا بعد انتهاء الدورة',
  fees:'الرسوم',
  setupFee:'رسوم الإعداد',
  accountingCode:'كود المحاسبة',
  redirectURL:'إعادة توجيه URL',
  redirectTo:'إعادة التوجيه إلى',
  planStatus:'حالة الخطة',
  exStarterPlan:'ex. Starter Plan',
  exStarterPlanAr:'مثال:الباقة الإفتتاحية',
  starterP:'StarterP',
  planForBeginning:'خطط للبداية الكبيرة',
  freeTrialHint:'قبل أيام من بدء الدورة',
  planNameHint:'plan Name Hint',
  planNameHintAr:'plan Name Hint Ar',
  redirectUrlHint:'إعادة توجيه URL',
  planCategory:'فئة الخطة',
  categoryDescription:'وصف التصنيف',
  categoryName:'اسم الفئة',
  exB2CCustomers:'ex. B2C Customers',
  categoryDescriptionPlaceholder:'تم إعداد هذه الخطة لعملاء B2C',
  categoryStatus:'Category Status',
  editCategory:'تعديل الفئه',
  categoryAddMsg:'تم أضافة التصنيف بنجاح ',
  categoryEditMsg:'تم تعديل التصنيف بنجاح ',
  model:"نموذج",
  fixedPrice:"سعر ثابت",
  dynamicPrice:"سعر متغير",
  SAR:"ريال"

};
